# MODEL
MODEL_PATH = (
    "/home/dlindberg/.cache/huggingface/hub/"
    "models--unsloth--Qwen3-30B-A3B-Instruct-2507-GGUF/snapshots/"
    "eea7b2be5805a5f151f8847ede8e5f9a9284bf77/"
    "Qwen3-30B-A3B-Instruct-2507-Q4_K_M.gguf"
)

# Seed for vLLM to allow deterministic cache reuse across runs
SEED = 132

# Enable/disable thinking mode
THINKING = False

# INFERENCE / SAMPLING
# MAX_TOKENS:       maximum number of output tokens that can be generated by a single sequence
# MAX_MODEL_LEN:    maximum number of input+output tokens a single sequence can occupy;
#   max_model_len * max_num_seqs = maximum input+output tokens in batch (KV-cache limit)
# MAX_NUM_BATCHED_TOKENS: maximum number of input tokens across a full batch
# MAX_NUM_SEQS:     maximum batch size (number of sequences processed in parallel)
# TOP_P:            nucleus sampling — only tokens whose cumulative probability exceeds this are considered
# TOP_K:            only the top-K most likely tokens are considered at each step
# MIN_P:            minimum probability a token must have relative to the top token to be considered
MAX_TOKENS = 1500
MAX_MODEL_LEN = 16000
MAX_NUM_BATCHED_TOKENS = 8192
MAX_NUM_SEQS = 25
TEMPERATURE = 0.7
GPU_MEMORY_UTILIZATION = 0.93
TOP_P = 0.8
TOP_K = 20
MIN_P = 0.01

# CLINGO
# CLINGO_MAX_MODELS:Cap model enumeration to detect severely under-constrained programs without hanging
# CLINGO_TIMEOUT:   Shared wall-clock budget for ground() and solve()
CLINGO_MAX_MODELS = 1001
CLINGO_TIMEOUT = 30.0

# REFINEMENT LOOP
# MAX_ATTEMPTS:     Number of reattempt iterations (attempt 0 = step 7; attempts 1..MAX_ATTEMPTS = refinement)
# SEVERELY_UNDERCONSTRAINED_THRESHOLD:
# Programs with more answer sets than this get a simplified "severely underconstrained" message
# MAX_VARIABLE_ATOMS: Limit variable atoms shown in semantic feedback to keep prompts manageable
MAX_ATTEMPTS = 1
SEVERELY_UNDERCONSTRAINED_THRESHOLD = 1000
MAX_VARIABLE_ATOMS = 30

# PIPELINE
DEFAULT_ENGINE = "qwen3-30b-local"

PROMPT_PATHS = {
    "constants": "prompts/2_constant_formatting.txt",
    "predicates": "prompts/3_gen_predicates.txt",
    "search_space": "prompts/4_gen_search_space.txt",
    "paraphrasing": "prompts/5_paraphrasing.txt",
    "constraints": "prompts/6_gen_constraints.txt",
    "reattempt": "prompts/8_reattempt.txt",
}

# Multi-turn prompt strings for constraint generation
CONSTRAINTS_SYSTEM = (
    "You are a semantic parser to turn clues in a problem into logical rules "
    "using only provided constants and predicates."
)
CONSTRAINTS_ASSISTANT_ACK = (
    "Ok. I will only write constraints under the provided forms."
)

# LOGGING
LOG_FORMAT = (
    "%(asctime)s [%(levelname)s] %(name)s - %(funcName)s:%(lineno)d > %(message)s"
)
ALLOWED_LOGGERS = ("__main__", "pipeline", "refinement_loop", "vllm_engine")
