#!/bin/bash

#SBATCH --job-name=EnvDown
#SBATCH --partition=rome
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --output=slurm_output_%A.out

module purge
module load 2025
module load Python/3.13.5-GCCcore-14.3.0
module load CMake/4.0.3-GCCcore-14.3.0

cd $HOME/Projects/asp-gen-refinements

# Initialize venv
python3 -m venv .venv
source .venv/bin/activate

echo "[SLURM] Installing vLLM requirements..."

# Build llama-cpp-python with CUDA GPU support
export CMAKE_ARGS="-DGGML_CUDA=on -DCMAKE_CUDA_ARCHITECTURES=80"
pip install --no-cache-dir -r requirements_vllm.txt

echo "[SLURM] Finished install. Proceeding with Clingo et al..."

# Needed as we're installing with no dependencies
pip install setuptools wheel scikit-build

export CMAKE_ARGS="-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
pip install --no-deps --no-build-isolation -r requirements.txt

echo "[SLURM] Exiting"
