"""vLLM engine for batched local inference with Qwen3-30B-A3B."""

import os
import re
import time

from logger import setup_logging, get_logger
from config import (
    MODEL_PATH,
    SEED,
    THINKING,
    MAX_TOKENS,
    MAX_MODEL_LEN,
    MAX_NUM_BATCHED_TOKENS,
    MAX_NUM_SEQS,
    TEMPERATURE,
    GPU_MEMORY_UTILIZATION,
    TOP_P,
    TOP_K,
    MIN_P,
)

setup_logging(log_level=os.getenv("LOG_LEVEL", "debug"))
logger = get_logger(__name__)


def _split_thinking(text):
    """Split raw vLLM output into (thinking, response).

    * thinking: content inside the first <think>...</think> block, or "" if absent
    * response: remaining text after stripping the thinking block

    Handles two cases:
    1. Full block in output: <think>...</think>response
    2. <think> was prepended to prompt, so output starts directly with thinking
       content and ends with </think>response (no opening tag in output).
    """
    thinking_re = re.compile(r"<think>(.*?)</think>", re.DOTALL)
    match = thinking_re.search(text)
    if match:
        thinking = match.group(1).strip()
        response = thinking_re.sub("", text).strip()
        return thinking, response

    # <think> was in the prompt; output begins with thinking content directly
    end_idx = text.find("</think>")
    if end_idx != -1:
        thinking = text[:end_idx].strip()
        response = text[end_idx + len("</think>"):].strip()
        return thinking, response

    return "", text.strip()


class VLLMEngine:
    def __init__(
        self,
        max_tokens=MAX_TOKENS,
        max_model_len=MAX_MODEL_LEN,
        max_num_batched_tokens=MAX_NUM_BATCHED_TOKENS,
        max_num_seqs=MAX_NUM_SEQS,
        temperature=TEMPERATURE,
    ):
        """
        * max_tokens: the maximum number of output tokens that can be generated by a single sequence.
        * max_model_len: the maximum number of input+output tokens a single sequence can occupy.
            - max_model_len * max_num_seqs = #maximum input+output tokens in batch.
            - This is essentially what might blow the KV-cache.
        * max_num_batched_tokens: the maximum number of input tokens for a full batch.
        * max_num_seqs: the maximum batch size.
        """
        from vllm import LLM, SamplingParams

        logger.info(f"Loading model from {MODEL_PATH}")
        t0 = time.perf_counter()
        self.llm = LLM(
            model=MODEL_PATH,
            max_model_len=max_model_len,
            max_num_seqs=max_num_seqs,
            max_num_batched_tokens=max_num_batched_tokens,
            gpu_memory_utilization=GPU_MEMORY_UTILIZATION,
            seed=SEED,
        )
        logger.info(f"Model loaded in {time.perf_counter() - t0:.2f}s")

        self.tokenizer = self.llm.get_tokenizer()
        self.sampling_params = SamplingParams(
            temperature=temperature,
            max_tokens=max_tokens,
            top_p=TOP_P,
            top_k=TOP_K,
            min_p=MIN_P,
        )

    def _apply_template(self, messages):
        """Apply chat template, enabling thinking mode for Qwen3.

        GGUF-embedded tokenizers silently ignore enable_thinking, so we
        manually append <think> to activate Qwen3 thinking mode when needed.
        """
        try:
            formatted = self.tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
                enable_thinking=THINKING,
            )
        except TypeError:
            formatted = self.tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )

        # GGUF tokenizers may silently ignore enable_thinking. For Qwen3,
        # thinking mode is activated by ending the prompt with <think>\n.
        if THINKING and not formatted.rstrip("\n").endswith("<think>"):
            formatted = formatted.rstrip("\n") + "<think>\n"

        return formatted

    def generate_batch(self, messages_list):
        """Generate responses for a batch of conversations.

        Args:
            messages_list: list of conversations, each a list of role/content dicts.

        Returns:
            list of (thinking, response) tuples where thinking is "" when absent.
        """
        formatted = [self._apply_template(msgs) for msgs in messages_list]

        logger.info(f"Generating batch of {len(formatted)} prompts...")
        t0 = time.perf_counter()
        outputs = self.llm.generate(formatted, self.sampling_params)
        t_gen = time.perf_counter() - t0

        # Counts all response tokens; both thinking and output
        n_tokens = sum(len(o.outputs[0].token_ids) for o in outputs)
        logger.info(
            f"Generated {n_tokens} tokens in {t_gen:.2f}s ({n_tokens / t_gen:.2f} tok/s)"
        )

        # Each response becomes tuple of (thinking, output)
        return [_split_thinking(o.outputs[0].text) for o in outputs]
