"""vLLM engine for batched local inference with Qwen3-30B-A3B."""

import os
import re
import time

from logger import setup_logging, get_logger
from config import (
    MODEL_PATH,
    SEED,
    THINKING,
    MAX_TOKENS,
    MAX_MODEL_LEN,
    MAX_NUM_BATCHED_TOKENS,
    MAX_NUM_SEQS,
    TEMPERATURE,
    GPU_MEMORY_UTILIZATION,
    TOP_P,
    TOP_K,
    MIN_P,
)

setup_logging(log_level=os.getenv("LOG_LEVEL", "debug"))
logger = get_logger(__name__)

_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL)


class VLLMEngine:
    def __init__(
        self,
        max_tokens=MAX_TOKENS,
        max_model_len=MAX_MODEL_LEN,
        max_num_batched_tokens=MAX_NUM_BATCHED_TOKENS,
        max_num_seqs=MAX_NUM_SEQS,
        temperature=TEMPERATURE,
    ):
        """
        * max_tokens: the maximum number of output tokens that can be generated by a single sequence.
        * max_model_len: the maximum number of input+output tokens a single sequence can occupy.
            - max_model_len * max_num_seqs = #maximum input+output tokens in batch.
            - This is essentially what might blow the KV-cache.
        * max_num_batched_tokens: the maximum number of input tokens for a full batch.
        * max_num_seqs: the maximum batch size.
        """
        from vllm import LLM, SamplingParams

        logger.info(f"Loading model from {MODEL_PATH}")
        t0 = time.perf_counter()
        self.llm = LLM(
            model=MODEL_PATH,
            max_model_len=max_model_len,
            max_num_seqs=max_num_seqs,
            max_num_batched_tokens=max_num_batched_tokens,
            gpu_memory_utilization=GPU_MEMORY_UTILIZATION,
            seed=SEED,
        )
        logger.info(f"Model loaded in {time.perf_counter() - t0:.2f}s")

        self.tokenizer = self.llm.get_tokenizer()
        self.sampling_params = SamplingParams(
            temperature=temperature,
            max_tokens=max_tokens,
            top_p=TOP_P,
            top_k=TOP_K,
            min_p=MIN_P,
        )

    def _apply_template(self, messages):
        """Apply chat template, disabling thinking mode if supported."""
        try:
            return self.tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
                enable_thinking=THINKING,
            )
        except TypeError:
            return self.tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )

    def generate_batch(self, messages_list):
        """Generate responses for a batch of conversations.

        Args:
            messages_list: list of conversations, each a list of role/content dicts.

        Returns:
            list of response strings (thinking tokens stripped).
        """
        formatted = [self._apply_template(msgs) for msgs in messages_list]

        logger.info(f"Generating batch of {len(formatted)} prompts...")
        t0 = time.perf_counter()
        outputs = self.llm.generate(formatted, self.sampling_params)
        t_gen = time.perf_counter() - t0

        n_tokens = sum(len(o.outputs[0].token_ids) for o in outputs)
        logger.info(
            f"Generated {n_tokens} tokens in {t_gen:.2f}s ({n_tokens / t_gen:.2f} tok/s)"
        )

        return [_THINK_RE.sub("", o.outputs[0].text).strip() for o in outputs]
