#!/bin/bash

#SBATCH --job-name=EnvDown
#SBATCH --partition=rome
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --output=slurm_output_%A.out

module purge
module load 2025
module load CUDA/12.8.0
module load Python/3.13.5-GCCcore-14.3.0

cd $HOME/Projects/asp-gen-refinements/testing

python3 -m venv .venv
source .venv/bin/activate

echo "Installing requirements..."
pip install -r requirements.txt
