#!/bin/bash

#SBATCH --job-name=QwenRun
#SBATCH --partition=gpu_a100
#SBATCH --time=01:00:00
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=72
#SBATCH --output=slurm_output_%A.out

module purge
module load 2025
module load CUDA/12.8.0
module load Python/3.13.5-GCCcore-14.3.0

cd $HOME/Projects/asp-gen-refinements/testing
source .venv/bin/activate

echo "Running local LLM test..."
python3 local_llm_test.py

echo ""
echo "Exiting job"
